import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import AuthProvider from "@/providers/auth-provider";
import QueryProvider from "@/providers/query-provider";
import {Toaster} from "@/components/ui/toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Chz",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                suppressHydrationWarning
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <QueryProvider>
                    <AuthProvider>
                        {children} <Toaster richColors />
                    </AuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
